# Generated by Django 4.0.6 on 2023-01-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikvah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='minutes_offset',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
