# Generated by Django 4.0.6 on 2023-04-30 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikvah', '0007_dayconfiguration_first_come_first_served_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='textable',
            field=models.BooleanField(default=False),
        ),
    ]
