# Generated by Django 4.0.6 on 2023-04-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mikvah', '0008_appointment_created_alter_appointment_textable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='created',
            new_name='created_at',
        ),
    ]
