# Generated by Django 4.0.6 on 2023-05-21 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mikvah', '0009_rename_created_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayconfiguration',
            name='closing',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
